version: "3.7"

services:
  traefik:
    image: traefik:2.6
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-global-proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      OVH_APPLICATION_KEY: ${OVH_APPLICATION_KEY}
      OVH_APPLICATION_SECRET: ${OVH_APPLICATION_SECRET}
      OVH_CONSUMER_KEY: ${OVH_CONSUMER_KEY}
      OVH_ENDPOINT: ${OVH_ENDPOINT} 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../script/docker/traefik/traefik.yml:/traefik.yml:ro
      - ../../script/docker/traefik/configurations:/configurations
      - /dev/disk/by-id/google-traefiksslpd:/etc/forge/traefik/acme
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-global-proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${FORGE_BASE_URL}`)"
#     - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  traefik-global-proxy:
    external: true

